export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const FETCH_TODO = 'FETCH_TODO'
export const DELETE_CARD = 'DELETE_CARD'
export const TOGGLE_ITEM = 'TOGGLE_ITEM'
export const SHOW_DETAIL = 'SHOW_DETAIL'
export const CLOSE_DETAIL = 'CLOSE_DETAIL'